version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: bigtree_app_docker/backend/Dockerfile
      args:
        timezone: ${BIGTREE_APP_TIMEZONE:-Asia/Seoul}
    image: ${COMPOSE_PROJECT_NAME:-bigtree_app}_backend_base
    command: cp -r /app/static/. /webroot/static
    volumes:
      - type: volume
        source: webroot
        target: /webroot

  backend_wsgi:
    image: ${COMPOSE_PROJECT_NAME:-bigtree_app}_backend_base
    command: [
      "poetry", "run",
      "hupper", "-m", "gunicorn.app.wsgiapp",
      "--workers=${WSGI_WORKERS:-2}",
      "--threads=${WSGI_THREADS:-4}",
      "--bind=backend_wsgi:8080",
      "--forwarded-allow-ips=webserver",
      "bigtree_app.wsgi:application"
    ]
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  frontend:
    build:
      context: .
      dockerfile: bigtree_app_docker/frontend/Dockerfile
      args:
        timezone: ${BIGTREE_APP_TIMEZONE:-Asia/Seoul}
    volumes:
      - type: volume
        source: webroot
        target: /webroot

  webserver:
    build:
      context: .
      dockerfile: bigtree_app_docker/webserver/Dockerfile
      args:
        timezone: ${BIGTREE_APP_TIMEZONE:-Asia/Seoul}
    ports:
        - "${BIGTREE_APP_PORT:-8080}:80"
    depends_on:
      - backend
      - backend_wsgi
      - frontend
    volumes:
      - ./media:/usr/share/nginx/html/media
      - type: volume
        source: webroot
        target: /usr/share/nginx/html

volumes:
  webroot:
