version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: bigtree_app_docker/backend/Dockerfile
      args:
        BIGTREE_APP_TIMEZONE: ${BIGTREE_APP_TIMEZONE:-Asia/Seoul}
    image: ${COMPOSE_PROJECT_NAME:-bigtree_app_template}_backend_base
    command: /bin/bash -c "rm -rf /frontend_static/*; cp -r /app/static/. /backend_static"
    volumes:
      - type: volume
        source: backend_static
        target: /backend_static

  backend_wsgi:
    image: ${COMPOSE_PROJECT_NAME:-bigtree_app_template}_backend_base
    command: [
      "poetry", "run",
      "hupper", "-m", "gunicorn.app.wsgiapp",
      "--workers=${WSGI_WORKERS:-2}",
      "--threads=${WSGI_THREADS:-4}",
      "--bind=backend_wsgi:8080",
      "--forwarded-allow-ips=webserver",
      "bigtree_app.wsgi:application"
    ]
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - type: volume
        source: media
        target: /app/media/

  frontend:
    build:
      context: .
      dockerfile: bigtree_app_docker/frontend/Dockerfile
      args:
        BIGTREE_APP_TIMEZONE: ${BIGTREE_APP_TIMEZONE:-Asia/Seoul}
        BIGTREE_APP_BACKEND_ONLY: ${BIGTREE_APP_DOCKER_BACKEND_ONLY:-false}
    command: /bin/bash -c "rm -rf /frontend_static/*; cp -r /app/build/. /frontend_static"
    volumes:
      - type: volume
        source: frontend_static
        target: /frontend_static

  webserver:
    build:
      context: .
      dockerfile: bigtree_app_docker/webserver/Dockerfile
      args:
        timezone: ${BIGTREE_APP_TIMEZONE:-Asia/Seoul}
    ports:
        - "${BIGTREE_APP_DOCKER_PORT:-8080}:80"
    depends_on:
      - backend
      - backend_wsgi
      - frontend
    volumes:
      - type: volume
        source: frontend_static
        target: /usr/share/nginx/html/frontend_static
      - type: volume
        source: media
        target: /usr/share/nginx/html/media
      - type: volume
        source: backend_static
        target: /usr/share/nginx/html/backend_static

volumes:
  frontend_static:
  backend_static:
  media:
