version: "3.7"

x-common:
  backend:
    &x-common-backend
    image: ${BIGTREE_APP_DOCKER_REGISTRY:-bigtree_app_template/}backend
    build:
      context: .
    env_file:
      - .env

services:
  backend:
    command: /bin/bash -c "rm -rf /static/backend/*; cp -r /app/static/. /static/backend; echo Copied backend static files to /static/frontend"
    volumes:
      - type: bind
        source: ./static
        target: /static
    <<: *x-common-backend

  frontend:
    image: ${BIGTREE_APP_DOCKER_REGISTRY:-bigtree_app_template/}frontend
    build:
      context: ./bigtree_app_frontend/
      args:
        TZ: ${TZ:-Asia/Seoul}
        BIGTREE_APP_DOCKER_DISABLE_FRONTEND_BUILD: ${BIGTREE_APP_DOCKER_DISABLE_FRONTEND_BUILD:-}
    command: /bin/bash -c "rm -rf /static/frontend/*; cp -r /app/build/. /static/frontend; echo Copied frontend static files to /static/frontend"
    volumes:
      - type: bind
        source: ./static
        target: /static

  wsgi:
    <<: *x-common-backend
    command: [
      "poetry", "run",
      "gunicorn",
      "--workers=${WSGI_WORKERS:-2}",
      "--threads=${WSGI_THREADS:-4}",
      "--bind=0.0.0.0:8080",
      "bigtree_app.wsgi:application"
    ]
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - type: bind
        source: ./media
        target: /app/media/
    restart: always
    env_file:
      - .env
    depends_on:
      - backend

  nginx:
    image: ${BIGTREE_APP_DOCKER_REGISTRY:-bigtree_app_template/}nginx
    build:
      context: ./bigtree_app_nginx/
    environment:
      - WSGI_HOST=wsgi
    ports:
        - "${BIGTREE_APP_DOCKER_PORT:-8080}:80"
    depends_on:
      - backend
      - frontend
      - wsgi
    volumes:
      - type: bind
        source: ./static
        target: /usr/share/nginx/html/static
      - type: bind
        source: ./media
        target: /usr/share/nginx/html/media
    restart: always
