module.exports = {
  preset: 'react-native-web',
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|svg)$': '<rootDir>/__mocks__/fileMock.js',
    '\\.(css|scss)$': '<rootDir>/__mocks__/styleMock.js',
  },
  moduleFileExtensions: [
    'web.js',
    'native.js',
    'android.js',
    'ios.js',
    'web.ts',
    'web.tsx',
    'native.ts',
    'native.tsx',
    'android.ts',
    'android.tsx',
    'ios.ts',
    'ios.tsx',
    'ts',
    'tsx',
    'js',
    'json',
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.init.js'],
};
